version: "3.9"
services:
  frontend:
    build: ./frontend
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app
    command: npm run dev
    # command: npm install
  backend:
    build: ./backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    command: uvicorn main:app --reload --host=0.0.0.0
